version: "3"
services:
  nats:
    image: nats-streaming
    ports:
      - 4222:4222
      - 8222:8222
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: 19U*@sYG%~%1O>^t
    ports:
      - 1433:1433
