apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: chat-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: chat/auth
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "1g"
