apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatsystem.fullname" . }}-webclient
  labels:
    app.kubernetes.io/name: {{ include "chatsystem.fullname" . }}-webclient
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-webclient
