apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deployment
  labels:
    app: chat-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      imagePullSecrets:
        - name: valhalla-cr
      containers:
        - name: chat
          image: cr.yggdrasill.dev/chat/session:19
          env:
            - name: MessageQueue__Url
              value: "nats://192.168.90.100:4222"
            - name: Redis__ConnectionString
              value: 192.168.90.100:6379
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
