apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deployment
  labels:
    app: chat-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
        - name: chat
          image: cr.yggdrasill.dev/chat/session:18
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
