apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: chat
          image: cr.yggdrasill.dev/chat/chat:10
          env:
            - name: MessageQueue__Url
              value: "nats://192.168.90.100:4222"
          resources:
            limits:
              cpu: "500m"
              memory: "1G"
