{{- $fullName := include "chatsystem.fullname" . -}}
{{- range .Values.ingress.hosts }}
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $fullName }}-{{ .host }}
spec:
  virtualhost:
    fqdn: {{ .host | quote }}
  routes:
  - conditions:
    - prefix: /ws
    enableWebsockets: true # Setting this to true enables websocket for all paths that match /websocket
    services:
    - name: {{ $fullName }}-connector
      port: 80
{{- end }}