name: Build & Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BuildConfiguration: debug
  ImageRegistry: cr.yggdrasill.dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: build auth
        env:
          DOCKER_HOST: tcp://localhost:2376
        run: dotnet build -c ${{env.BuildConfiguration}} -t:ContainerBuild -p:DockerfileTag=${{env.ImageRegistry}}/chat/auth:${{github.run_number}} --no-restore AuthServer/AuthServer.csproj
